config/routes.rb
Rails.application.routes.draw do
 
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations' ,:sessions => 'users/sessions'}
  resources :home, only: [:list_lip] #for pagination

  
  root 'home#index' #랜딩페이지 메인
  get 'home/index'

  
  get 'home/search'

  get 'home/basket'
  get '/basket' => 'home#basket'
  post 'home/basket_delete'
  get 'home/:list_num/basket_delete/' => 'home#basket_delete'
  get 'home/season_update'
  get 'season_update' => 'home#season_update'
  post 'home/userseason_update'
  
  
  get 'home/list_lip2'
  get 'home/list_lip2/:tone'  => "home#list_lip2"  # 립 리스트에서 카테고리 값 부여
  
  

  
  
  
  

  get 'home/write_review/:product_num' => 'home#write_review' #리뷰쓰기
  post 'home/review_submit' #리뷰등록
  get 'update_view/:product_num/:review_id' => "home#update_view" #리뷰수정하기
  post 'home/review_update_submit/:review_id' => "home#review_edit" #수정한리뷰등록
  get  'destroy_review/:review_id' => "home#destroy_review" #리뷰삭제
 
  
  
  get '/adminadmin' => 'home#admin_user'
  get 'home/admin_reply' #admin_리뷰모아보기
  get 'home/admin_user' #admin_회원모아보기
  get 'home/admin_write'
  get 'home/admin_feedback'#재검토요청 모아보기
  get 'home/admin_likes' #찜현황 모아보기
   
  get 'home/feedback/:product_num' => "home#feedback"
  post 'home/feedback_submit'
  
 
  get 'home/detail2/:tone/:product_num' => "home#detail2"
  get 'home/detail2/:product_num' => "home#detail2"
  
  post 'home/update_history'
  
  post 'home/askfor_submit'  #문의/건의
  post 'home/askfor_submit2' #제품요청

  get 'askfor_delete/:askfor_id' => 'home#askfor_delete' # 제품요청 삭제
  post 'askfor_status/:askfor_id' => 'home#askfor_status' # 제품요청 상태 변경

  get 'home/request_list'
  get 'home/request_write'
  post 'home/request_write_ok'
  get 'home/request_view/:request_id' => 'home#request_view'
  get 'home/request_destroy/:request_id' => 'home#request_destroy'
  get 'home/request_update/:request_id' => 'home#request_update'
  post 'home/request_update_ok/:request_id' => 'home#request_update_ok'

  post 'home/comment_create'
  get 'home/comment_destroy/:comment_id' => 'home#comment_destroy'
  get 'home/comment_update/:comment_id' => 'home#comment_update'
  
  get 'home/request_reply/:request_id' => 'home#request_reply'
  post 'home/request_reply_ok'
  get 'home/request_reply_view/:request_id' => 'home#request_reply_view'
  get 'home/request_reply_destroy/:request_id' => 'home#request_reply_destroy'
  get 'home/request_reply_update/:request_id' => 'home#request_reply_update'
  post 'home/request_reply_update_ok/:request_id' => 'home#request_reply_update_ok'
  
  get 'home/request_pwd_check/:request_id&current_page=:current_page' => 'home#request_pwd_check'
  post 'home/request_pwd_confirm/:request_id&current_page=:current_page' => 'home#request_pwd_confirm'
  get 'home/request_reply_pwd_check/:request_id' => 'home#request_reply_pwd_check'
  post 'home/request_reply_pwd_confirm/:request_id' => 'home#request_reply_pwd_confirm'

  get 'home/notice'
  post 'home/notice_write'
  get 'home/notice_view/:notice_id' => 'home#notice_view'

  get 'home/notice_edit/:notice_id' => 'home#notice_edit'
  post 'home/notice_edit_back/:notice_id' => 'home#notice_edit_back'

  get 'home/notice_delete/:notice_id/' => 'home#notice_delete'

  resources :home do 
    member do
      get "like"
      get "unlike"
    end
  end

  resources :home do 
    member do
      get "recommend"
      get "norecommend"
      get "disrecommend"
      get "nodisrecommend"
      get "recommend2"
      get "norecommend2"
      get "disrecommend2"
      get "nodisrecommend2"
    end
  end

  
  resources :home do 
    member do
      get "basket_delete"
      
    end

  end

 
 

end

app/controllers/home_controller.rb
require 'rails_autolink'
class HomeController < ApplicationController

  include ApplicationHelper
  
  def index

    #공지사항 최신글 보여주기
    @news = Notice.order('id desc').first(5)

    #총 제품 개수
    @product_count = Lip.count


    #이번주 등록 제품 개수

    #@update_count = Lipdb.where(:id => 200..236).count
    #@update_count = 0

    #제품 요청
    #@asks = Askfor.order('id desc').paginate(page: params[:page], per_page: 5)


  end

# main은 에전에 BEST 제품 노출하던 layout

#  def main
#    # 웜 립 TOP3
#    @w_best_lip = Lipdb.get_w_lip.order('zzim desc').first(3)
#    # 웜 섀도 TOP3
#    @w_best_sha = Eyedb.get_w_eye.order('zzim desc').first(3)
#    # 쿨 립 TOP3
#    @c_best_lip = Lipdb.get_c_lip.order('zzim desc').first(3)
#    # 쿨 섀도 TOP3
#    @c_best_sha = Eyedb.get_c_eye.order('zzim desc').first(3)

#  end
  

  def search
    # splitting the search key word
    if params[:search].include?(" ") == true
      @search = params[:search].split(" ").first
      @search2 = params[:search].split(" ").second
      @search3 = params[:search].split(" ").third
    else
      @search = params[:search]
    end   

    if params[:search]
      @result = Lip.all.search(@search,@search2,@search3).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 21)
    else
      @result = Lip.all.order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 21)
    end
    
    if params[:tone]
      @current_season = params[:tone]
    else
      @current_season = "default"
    end

  end
  
  
  def list_lip


  #빵부스러기 목록
  if params[:tone]
    @current_season = params[:tone]
    @list = Lipdb.where(season_total: params[:tone]).order('brand').paginate(page: params[:page], per_page: 21)
  else
    @current_season = "봄 브라이트"
  end
  
  
  # 8 분류에 따른 립 카테고리 설정
#  if params[:tone]
#    @list=Lipdb.where(season_total: params[:tone]).order('brand').paginate(page: params[:page], per_page: 21)

#    @list=Lipdb.where(season_total: params[:tone])
#    .where(color: params[:color]).where(texture: params[:texture])
#    .where(brand: params[:brand]).order('brand').paginate(page: params[:page], per_page: 21)
# end


  
#  if params[:tone] || params[:texture] 
  
#   @list=Lipdb.where(season_total: params[:tone]).where(texture: params[:texture]).order('brand').paginate(page: params[:page], per_page: 21)
   ## @list=Lipdb.where(season_total: params[:tone])
    ##.where(texture: params[:texture]).where("brand LIKE ?","%#{params[:brand]}%").order('brand').paginate(page: params[:page], per_page: 21)
#  end
  


  # 12분류 기준일때는 봉인 (16.11.08)

    # 웜톤 립 출력
 #   if params[:colors] == "w_lips"
      #웜립일때
 #     @colors = "w_lips"
 #     @color_tone = "웜"
     # @liplist = params[:liplist]
 #     @liptone ||= params[:liptone]
      #웝립/제품군/세부톤
 #     @list = Lipdb.get_w_lip.where(tone:params[:liptone]).order('brand').paginate(page: params[:page], per_page: 21)
   # if params[:liplist] == nil
    #   @liplist = "제품"
     #  @list = Lipdb.get_w_lip.where(tone:params[:liptone]).order('brand').paginate(page: params[:page], per_page: 21)
  #    if params[:liptone] == nil
  #        @liptone = "세부톤 전체보기"
  #        @list = Lipdb.get_w_lip.order('brand').paginate(page: params[:page], per_page: 21)
  #    end
  #   end
      #세부톤 선택안했을때
  #   if params[:liptone] == nil
  #      @liptone = "세부톤"
        #웜립/제품군에 따라 출력
  #      @list = Lipdb.get_w_lip.where(pro_type:params[:liplist]).order('brand').paginate(page: params[:page], per_page: 21)
         #세부톤,제품군 선택안했을때 웜립 전체출력
  #      if params[:liplist] == nil
  #        @liplist = "제품"
  #        @list = Lipdb.get_w_lip.order('brand').paginate(page: params[:page], per_page: 21)
  #      end
  #    end
  #  end

  #  # 쿨톤 립 출력
  #  if params[:colors] == "c_lips"
  #    @colors = "c_lips"
  #    @color_tone = "쿨"
    #  @liplist = params[:liplist]
  #    @liptone = params[:liptone]
  #    @list = Lipdb.get_c_lip.where(tone:params[:liptone]).order('brand').paginate(page: params[:page], per_page: 21)
    #  if params[:liplist] == nil
    #    @liplist = "제품"
    #    @list = Lipdb.get_c_lip.where(tone:params[:liptone]).order('brand').paginate(page: params[:page], per_page: 21)
  #      if params[:liptone] == nil
  #        @liptone = "세부톤 전체보기"
  #        @list = Lipdb.get_c_lip.order('brand').paginate(page: params[:page], per_page: 21)
  #      end
  #  end

   #   if params[:liptone] == nil
   #     @liptone = "세부톤"
   #     @list = Lipdb.get_c_lip.where(pro_type:params[:liplist]).order('brand').paginate(page: params[:page], per_page: 21)
   #     if params[:liplist] == nil
   #       @liplist = "제품"
   #       @list = Lipdb.get_c_lip.order('brand').paginate(page: params[:page], per_page: 21)
   #     end
   #   end
   # end

  end
  
  def list_lip2

    #립 리스트 제목
    if params[:tone]
      @current_season = params[:tone]
    else
      @current_season = "봄 브라이트"
    end
    
    
    #계절 톤을 구성하는 세부톤 알려주기
  
    @tone_detail = case @current_season
    
      when "봄 브라이트" then "브라이트, 비비드"
      when "봄 라이트" then "페일, 라이트"
      when "여름 라이트" then "페일, 라이트"  
      when "여름 뮤트" then "라이트 그레이시, 소프트, 그레이시, 덜"  
      when "가을 뮤트" then "라이트 그레이시, 소프트, 그레이시, 덜"   
      when "가을 딥" then "스트롱, 딥, 다크, 다크 그레이시"
      when "겨울 딥" then "딥, 다크, 다크 그레이시"
      when "겨울 브라이트" then "브라이트, 비비드, 스트롱"
    
    end
            
    

    #lip.rb에 있는 메소드 사용

    #필터 검색

    @list = Lip.where(nil).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) # creates an anonymous scope

    @list = @list.tone(params[:tone]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:tone].present?

    @list = @list.pro_type(params[:pro_type]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:pro_type].present?

    @list = @list.color(params[:color]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20)if params[:color].present?

    @list = @list.texture(params[:texture]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:texture].present?

    @list = @list.level(params[:level]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:level].present?

    #브랜드 필터(드롭박스) 검색
    
    if params[:brand].present?
      
    @list = @list.brand(params[:brand]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) 
    
    @list = @list.brand(params[:brand]).tone(params[:tone]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:tone].present?
    
    @list = @list.brand(params[:brand]).pro_type(params[:pro_type]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:pro_type].present?
    
    @list = @list.brand(params[:brand]).color(params[:color]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:color].present?
    
    @list = @list.brand(params[:brand]).level(params[:level]).order(update_date: :desc, brand: :asc).paginate(page: params[:page], per_page: 20) if params[:level].present?

    end
    


  end


  def detail
    
    #립 상세페이지
    if params[:product_num].start_with?("L")
      @product = Lipdb.find_by_image(params[:product_num])
    end

    
   # 좋아요 페이지 (like.js.erb)로 갔다가 redirect 됐을때 좋아요 수를 lip,eye db의 zzim에 저장
   # @product.zzim = @product.votes_for.up.by_type(User).size
   # @product.save
    
    # 리뷰 작성 시에 해당 제품의 리뷰 페이지로 연결될 수 있도록 변수 지정
    @review=Review.where(num:params[:product_num])



  end

  #=====진단 히스토리 시작=====
  def update_history
 
    @update_history = UpdateHistory.new
    @update_history.num = params[:num]
    @update_history.title = params[:title]
    @update_history.content = params[:content]
    @update_history.save
      
    redirect_to :back

  end
  
  #=====진단 히스토리 끝======
  
  def detail2
    
    # 빵부스러기
    #if params[:product_num]
    #  @current_season = Lip.find_by_image(params[:product_num])
    #else
    #  @current_season = "봄 브라이트"
    #end
    
    #립 상세페이지
    if params[:product_num]
      @product = Lip.find_by_image(params[:product_num])
    end

    if params[:tone]
      @current_season = params[:tone]
    else
      @current_season = "default"
    end


    # 좋아요 페이지 (like.js.erb)로 갔다가 redirect 됐을때 좋아요 수를 lip,eye db의 zzim에 저장
     #@product.zzim = @product.votes_for.up.by_type(User).size
     #@product.save
    
    #추천수1
    @recommend_count = @product.get_likes(:vote_scope => 'recommend').size
    #비추천수1
    @disrecommend_count = @product.get_dislikes(:vote_scope => 'recommend').size
    
     #추천수2
    @recommend2_count = @product.get_likes(:vote_scope => 'recommend2').size
    #비추천수2
    @disrecommend2_count = @product.get_dislikes(:vote_scope => 'recommend2').size
    
    
    # 리뷰 작성 시에 해당 제품의 리뷰 페이지로 연결될 수 있도록 변수 지정
    @review=Review.where(num:params[:product_num]).order("id desc").paginate(page: params[:page], per_page: 5)
    
    #진단 히스토리
    @update_histories=UpdateHistory.where(num:params[:product_num]).order("id asc")

  end  
  #================= 아래는 좋아요 기능=====================
  def like 
    
    if params[:id].start_with?("L") 
      @product = Lip.find_by_image(params[:id])   #find_by_image 에서 image는 제품 데이터의 고유의 값(현재는 L006이런게 엑셀 상 image 열에 있어서 image임)
    end
    
    @product.liked_by current_user, :duplicate => true #찜하기의 총 누적 흔적 세기 위해서 duplicate 옵션 추가
  
    #@product.zzim = @product.votes_for.up.by_type(User).size #좋아요 수를 lip,eye db의 zzim에 저장
    #@product.save
    
    
      
    respond_to do |format|
      #format.html { redirect_to :back }
      format.js
    end
  end  

  def unlike
    
    if params[:id].start_with?("L") 
      @product = Lip.find_by_image(params[:id])
    end
    
    #@product.unliked_by current_user
     @product.downvote_from current_user,:duplicate => true #찜하기의 총 누적 흔적 세기 위해서 duplicate 옵션 추가

app/helpers/home_helper.rb
module HomeHelper
  
  def display_likes(product)
    votes = product.votes_for.up.by_type(User)
    return count_likers(votes)
    
  end

  def liked_product(product)  
    return 'glyphicon-heart' if current_user.voted_for? product
    'glyphicon-heart-empty'
  
  end
  
  def unliked_product(product)  
    return 'glyphicon-heart-empty' unless current_user.voted_for? product
    'glyphicon-heart'
  end
  

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s
  end



end

app/views/home/admin_feedback.html.erb
<!--admin page : 재검토요청 모아보기-->
    <div class="admin_button_wrapper">
     <input type="button" value="회원목록" class="button" onclick="window.location='/home/admin_user';">
     <!--<input type="button" value="리뷰보기" class="button" float="left" onclick="window.location='/home/admin_reply';" >-->
     <input type="button" value="재검토요청" class="button" onclick="window.location='/home/admin_feedback';" >
     <input type="button" value="찜 현황판" class="button" onclick="window.location='/home/admin_likes';" >
     <input type="button" value="문의/건의" class="button" onclick="window.location='/home/request_list';" >
     <input type="button" value="공지 작성" class="button" onclick="window.location='/home/admin_write';" >
         
      <a href="/users/sign_out">관리자 로그아웃</a>
    </div>
    
    <h3 align="center">재검토 요청 모아보기</h3>
    
      <div class="container container-up-margin">
          <ul class="media-list forum">

            <% @review.each do |p| %>

              <li>
                <!-- 리뷰본 -->
                <div class="media">
                    <div class="col-md-12 col-xs-12">
                      <div class="col-md-12" >
                        <p style="text-align:left;"><a href="/home/detail2/<%=p.pro_num%>"><%=p.pro_num%></a></p>
                        <p style="text-align:left;"><%=p.created_at.in_time_zone("Asia/Seoul").strftime("%Y/%m/%d/ %H:%M:%S") %></p>
                        <p style="text-align:left;"><%=p.emailaddress%></p>
                      </div>
                     
                    <div class="col-md-12 col-xs-12">
                      <div class="col-md-9 col-xs-9">내용: <%=p.content %></div> 
                        <% unless p.img_url.nil? %>
                          <img class="review_img" src="<%= p.img_url %>">
                        <% end %>
                      </div>
                    </div>
                </div>
              </li>
            <%end%>
          </ul>
        <%= render :partial => "layouts/partial/pagination" %>
      </div>
  

app/views/home/disrecommend.js.erb
alert('비공감 하였습니다.');
$("#<%= @product.image %>_disrecommend").removeClass('fa-thumbs-o-down').addClass('fa-thumbs-down');
$("#<%= @product.image %>_disrecommend").attr("href", '/home/<%= @product.image %>/nodisrecommend');
$("#recommend").load(location.href + " #recommend");

app/views/home/disrecommend2.js.erb
alert('비공감 하였습니다.');
$("#<%= @product.image %>_disrecommend2").removeClass('fa-thumbs-o-down').addClass('fa-thumbs-down');
$("#<%= @product.image %>_disrecommend2").attr("href", '/home/<%= @product.image %>/nodisrecommend2');
$("#recommend2").load(location.href + " #recommend2");

app/views/home/layout5.erb
<!-- 상세페이지 -->
<div class="container">
  <div style = "margin-top:40px">
    <div class="row">
      
      <div class="col-md-6 col-xs-12 carousel slide item active" id="carousel-example-generic" data-ride="carousel" style="padding-right:50px; padding-left:50px">
        <img class="img1 img-thumbnail" width=400 src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/lip/<%=@product.num%>.jpg">
      </div>
    
      <div class="col-md-6 col-xs-12"  id="orange" style="padding-top:10px; margin-left:-15px;">
        <h4>[<%=@product.brand %>]</h4>
        <h3><strong><%=@product.name %></strong></h3> <!-- 해당 페이지만 브랜드명, 제품명, 용량/가격 -->
        <h4><%=@product.size %> / <%=@product.price %>원</h4>
    
        <!--좋아요 기능 작동하는 하트 버튼 노출-->
        <%if user_signed_in?%>    
          <% if current_user.voted_up_on? @product %>
            <div class="row" style="text-align:right">  
              <div class="col-sm-1 col-sm-offset-10 unlike-button" style="position:right">
                <%= link_to '', unlike_home_path(@product.num), remote: true, id: "#{@product.num}_like", 
                    class: "like fa fa-heart" %>
              </div>
            </div>  
          <% else %>
            <div class="row" style="text-align:right"> 
              <div class="col-sm-1 col-sm-offset-10 like-button" style="position:right">
                <%= link_to '', like_home_path(@product.num), remote: true, id: "#{@product.num}_like",
                    class: "like fa fa-heart-o" %> 
              </div>
            </div>  
          <% end %>
          <!--/좋아요 기능 작동하는 하트 버튼 -->
                      
        <%else%>
          <!--로그인을 안 했을 시 로그인을 유도하는 가짜 찜하기 버튼 -->
          <div class="row">
            <div class="col-sm-1 col-sm-offset-10 fake-like-button" align="right">
              <%= link_to "", new_user_session_path, data: { confirm: "로그인 후 이용해주세요." },  id: "fake-like",
                  class: "fa fa-heart-o"%>
            </div>
          </div>
        <%end%>      
 
        <hr style="border:solid 1px lightgray;">
        <div>
          <div class="col-md-6 col-xs-6" style="padding-top:5px;">
            <h4 style="text-align: center"> <strong>톤</strong> <%=@product.tone %></h4><br>
            <img class="p hidden-xs" src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/icon/tone/<%=@product.tone%>.png" width="80%" style="margin-left:18px">
          </div>
          <div class="col-md-6 col-xs-6" style="padding-top:5px">
            <h4 style="text-align: center"> <strong>타입</strong> <%=@product.wc %></h4><br>
            <img class="c hidden-xs" src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/icon/<%=@product.wc %>.png" width="95%"style="margin-left:10px" >
          </div>    
        </div>
      </div>
                
    
    </div>
  </div>
        
  <br> 
  <hr style="border: solid 0.2px lightgray;"> <!--가로선-->
  <br>
        
  <!-- 제품군, 펄유무, 텍스쳐-->
  <div style="margin-right:-20px; margin-top:-20px">
    <div class="panel panel-default col-md-4 col-xs-4">
      <div class="panel-body" align="center">
        <span style="font-size:12px; text-align:center">
        <img src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/icon/product_lip.png" width="30"><br><%=@product.pro_type %></span>
      </div>
    </div>
    <div class="panel panel-default col-md-4 col-xs-4">    
      <div class="panel-body" align="center">
        <span style="font-size:12px; text-align:center">
        <img src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/icon/glitter.png" width="30"><br><%=@product.glitter %></span>
      </div>
    </div>
    <div class="panel panel-default col-md-4 col-xs-4">
      <div class="panel-body" align="center">
        <span style="font-size:12px; text-align:right">
          <img src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/icon/texture.png" width="30"><br><%=@product.texture %></span>
      </div>
    </div>
  </div>

  <br><br>
  <!-- 수정요청 버튼 들어갈 부분 -->
  <hr style="border: solid 0.2px lightgray;">
    <% if user_signed_in? %>
      <div id="two" style="text-align:right; margin-bottom:40px;">
        <a href="/home/feedback/<%=@product.num%>" style="color:#ffffff;" class="btn btn-black" role="button">수정요청</a> <!-- button 으로 하면 페이지 이동이 안됨;; 왜그러지-->
      </div>
    <% else %>
      <a href="/users/sign_in" style="color:#ffffff;" class="btn btn-black" role="button">[수정요청]</a>
    <% end %>
        
  <br><br>
        
  <div class="container">
    <h1 class="page-header"><i class="fa fa-pencil"></i> Review</h1>
    <p class="lead">후기를 작성해보세요!</p>
    <div>
      <ul class="media-list forum">
        <!-- 리뷰db에서 상품num으로 불러오기 (p.어쩌구는 절대건드리지말것!!! db관련된거임!!) -->
        <% @review.each do |p| %>
          <li>
            <!-- 후기작성자정보(왼쪽)-->
            <div class="pull-left user-info" href="#" float="left">
              <!-- 프로필사진(계절타입) -->
              <img src="https://s3.ap-northeast-2.amazonaws.com/fourseasons111112/icon/seasonicon/<%= p.userseason %>.png" width="64" style="margin-left:15px" >                        
              <br/>
              <!-- 작성자닉네임-->
              <strong><center><a href="user.html"><%=p.username%></a></center></strong>
              <!-- 작성자계절타입-->
              <small><center><%=p.userseason%></center></small>
            </div>
            <!-- 리뷰본문(오른쪽) -->
            <div class="media" style="border: 0px solid lightgray; border-radius: 5px; padding:10px; background-color:#f5f5f5;">
                <div class="col-md-12">
                  <div class="col-md-12" style="top:0px; right:0px; text-align:right;"><%= p.created_at.strftime("%Y-%m-%d") %></div>
                    <!-- 첨부된사진 -->  
                    <div class="col-md-3" style="margin-top:20px;">
                      <% if p.img_url == nil %>
                        <img width="100%" src="https://s3.ap-northeast-2.amazonaws.com/likelion1111/uploads/noimages.jpg">
                      <% else %>
                        <img width="100%" src="<%= p.img_url %>">
                      <% end %>
                    </div>
                    <br><br>
                    <!-- 후기내용 -->
                    <div class="col-md-9"><%=p.content %></div>
                </div><br>
                  <!-- 작성날짜 -->
                  <div class="col-md-12" style="text-align:right;">
                    <!-- 수정하는 페이지로 이동-->
                    <a href="/update_view/<%=@product.num%>/<%=p.id%>">[수정하기]</a>
                    <!-- 삭제버튼-->
                    <% if p.username = current_user.username %>
                      <a href="/destroy/<%= p.id %>">[삭제]</a> <!-- 글작성자가 현재로그인한유저면 삭제버튼 보임 -->
                    <% else %>
                      <!--근데 닉네임 중복불가를 설정해놔야할듯. 같은닉네임이 있으면 여기서 문제생길듯.. -->
                   <% end %>
                  </div>
            </div>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
  <br><br>
  
  <% if user_signed_in? %> <!-- 로그인 시 , 후기작성하는 페이지로 이동 -->
    <center><a href="/home/write_review/<%=@product.num%>" class="btn btn-black btn-lg active" style="color:#ffffff" role="button" aria-pressed="true">후기 작성하기</a></center>
  <% else %> <!-- 로그인 안했으면 로그인페이지로 이동 -->
    <center><a href="/users/sign_in" id="review_login" class="btn btn-black btn-lg active" style="color:#ffffff" role="button" aria-pressed="true">후기 작성하기</a></center>
  <% end %>
                      
</div>


<style>
    @import url(http://fonts.googleapis.com/earlyaccess/hanna.css);
    h4 {font-family: 'Hanna';}
    
    .btn-black{
        width:relative;
        height:40px;
        font-size:15px;
        text-align:center;
        cursor:pointer;
        background:#333333;
    }
</style>
   
<script>
    
      //제품 드롭다운
    $('#divNewNotifications li').on('click', function() { 
          $('#dropdown_title').html($(this).find('a').html());
        });
        
    //세부톤 드롭다운
    $('#divNewNotifications2 li').on('click', function() {
          $('#dropdown_title2').html($(this).find('a').html());
        });  
    
    //로그인 안한상태에서 후기쓰기 누르면 뜨는 안내메세지    
    $("#review_login").click(function(){
      alert("로그인 후 이용해주세요!");
    });	
</script>

app/views/home/nodisrecommend2.js.erb
alert('취소 되었습니다.');
$("#<%= @product.image%>_disrecommend2").removeClass('fa-thumbs-down').addClass('fa-thumbs-o-down');
$("#<%= @product.image %>_disrecommend2").attr("href", '/home/<%= @product.image %>/disrecommend2');
$("#recommend2").load(location.href + " #recommend2");

app/views/home/unlike.js.erb
alert('관심상품 목록에서 제거 되었습니다.');

<!--$(".<%#= @product.image%>_like").removeClass('fa-heart').addClass('fa-heart-o');-->

$(".img_heart_on").attr("src", "<%= image_path 'btn_heart_off.png' %>" );
$(".img_heart_on").attr("alt", "img_heart_off" );
$(".img_heart_on").removeClass('img_heart_on').addClass('img_heart_off');

$(".<%= @product.image %>_like").attr("href", '/home/<%= @product.image %>/like');


<!--$("#<%= @product.image %>_like").html("<%= j (render partial: 'home/unlikes', locals: { product: @product } ) %>");-->